# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Compose Companion
theme:
  features:
    - navigation.tabs
  name: material
  palette:
    scheme: slate
    primary: deep purple

repo_url: https://github.com/bohregard/Compose-Companion
repo_name: bohregard/Compose-Companion
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true